version: "3"
services:
  strapi:
    command: sh -c 'rm -rf /home/node/app/node_modules/* && npm run develop'
    build:
      context: ../cms
      dockerfile: ../deployment/strapi/Dockerfile
    env_file: ./strapi/strapi.env.default
    volumes:
      - ../cms:/home/node/app
      - exclude:/home/node/app/node_modules
    restart: on-failure

  nginx:
    image: nginx:1-alpine-slim
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 127.0.0.1:4567:80

volumes:
  exclude:
