#!/bin/sh -eu

docker build -f Dockerfile.update-package-lock -t update-package-lock .
docker create --name extract update-package-lock
docker cp extract:/home/node/package-lock.json .
docker rm extract